{% set name = "grandalf" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bdcht/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b3112299fe0a9123c088a16bf2f1b541d0d91199b77170a9739b569bd16a828e

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install --no-deps . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
  run:
    - python >={{ python_min }}
    - pyparsing
    - future

test:
  requires:
    - python {{ python_min }}
  imports:
    - grandalf

about:
  home: https://github.com/bdcht/grandalf
  license: GPL-2.0 OR EPL-1.0
  license_file: LICENSE
  summary: 'Graph and drawing algorithms framework'

  # The remaining entries in this section are optional, but recommended.
  description: |
    Grandalf is a Python package made for experimentations with graphs and drawing
    algorithms. It is written in pure python.
  dev_url: https://github.com/bdcht/grandalf

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
