{% set name = "grandalf" %}
{% set version = "0.55555" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bdcht/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 00ce44051a9bcd228978a5132fb1fd13d24f1ea561ba7590bf797c8fa7ed2c33

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - pyparsing
    - future

test:
  imports:
    - grandalf

about:
  home: https://github.com/bdcht/grandalf
  license: GPL-2.0 OR EPL-1.0
  license_file: LICENSE
  summary: Graph and drawing algorithms framework

  # The remaining entries in this section are optional, but recommended.
  description: |
    Grandalf is a Python package made for experimentations with graphs and drawing
    algorithms. It is written in pure python.
  dev_url: https://github.com/bdcht/grandalf

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
